# Generated by Django 5.1.3 on 2024-11-30 01:28

"""
Migration script to create the SpotifyWrap and Wrap models.

This script defines the initial database schema for the SpotifyWrap and Wrap
models, including their fields and relationships with the user model.
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Represents the migration for initializing the SpotifyWrap and Wrap models.

    Attributes:
        initial (bool): Indicates that this is the initial migration.
        dependencies (list): Lists the migration dependencies.
        operations (list): Contains the database operations to be executed.
    """

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyWrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),  # Name of the Spotify wrap
                ('time_frame', models.CharField(max_length=50)),  # Time range for the wrap
                ('created_at', models.DateTimeField(auto_now_add=True)),  # Timestamp of creation
                ('data', models.JSONField()),  # JSON field to store Spotify data
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='spotify_wraps',
                    to=settings.AUTH_USER_MODEL
                )),  # Foreign key linking to the user
            ],
        ),
        migrations.CreateModel(
            name='Wrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),  # Name of the generic wrap
                ('created_at', models.DateTimeField(auto_now_add=True)),  # Timestamp of creation
                ('data', models.JSONField()),  # JSON field to store wrap data
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='wraps',
                    to=settings.AUTH_USER_MODEL
                )),  # Foreign key linking to the user
            ],
        ),
    ]
