# Generated by Django 5.1.2 on 2024-11-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifywrap',
            old_name='wrap_data',
            new_name='top_artists',
        ),
        migrations.AddField(
            model_name='spotifywrap',
            name='top_genres',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spotifywrap',
            name='top_tracks',
            field=models.JSONField(default=100),
            preserve_default=False,
        ),
    ]
