# Generated by Django 5.1.2 on 2024-11-21 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0002_rename_wrap_data_spotifywrap_top_artists_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifywrap',
            old_name='top_artists',
            new_name='wrap_data',
        ),
        migrations.RemoveField(
            model_name='spotifywrap',
            name='top_genres',
        ),
        migrations.RemoveField(
            model_name='spotifywrap',
            name='top_tracks',
        ),
    ]
