# Generated by Django 5.1.2 on 2024-11-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0003_rename_top_artists_spotifywrap_wrap_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifywrap',
            old_name='wrap_data',
            new_name='top_artists',
        ),
        migrations.AddField(
            model_name='spotifywrap',
            name='top_genres',
            field=models.JSONField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spotifywrap',
            name='top_tracks',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
