# Generated by Django 5.1.2 on 2024-11-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0005_alter_spotifywrap_user_wrap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifywrap',
            old_name='top_artists',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='spotifywrap',
            name='top_genres',
        ),
        migrations.RemoveField(
            model_name='spotifywrap',
            name='top_tracks',
        ),
        migrations.AddField(
            model_name='spotifywrap',
            name='time_frame',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
