# Generated by Django 5.1.2 on 2024-11-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0006_rename_top_artists_spotifywrap_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifywrap',
            name='name',
            field=models.CharField(default='New Wrap', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spotifywrap',
            name='time_frame',
            field=models.CharField(max_length=50),
        ),
    ]
